### PR TITLE
Update print for python3 and remove unnecessary code for type conversion

### PR DESCRIPTION
**Pull request by Authentic10**
- **print** without parentheses not working with python3 so I added the parentheses 
- There were some type conversion on the k variable which is already of type int into int using the pandas' **astype** method and it was generating an error some I remove them too

### CODE REVIEW

**Comment by Authentic10** [comment]
Hi, unfortunately no.
I hope you were able to get through it.

**Comment by willgoldby** [comment]
Hi Ahmed, 

Sorry for the delay. 

This pull request has changes related to the Colab's status. For example, see line [48](https://github.com/google/eng-edu/pull/59/files#diff-8d76fbc231da6b648dc461d0ed379b87ecac2f3161e6e1c9abbfb5edfe346e56L48).

We can merge the pull request after those changes aren't reflected in the commit. 

Thanks.

**Comment by Imokut** [comment]
embarrassing that I've noticed this issue in a couple of the notebooks

**Comment by willgoldby** [comment]
Hi there! Thanks for your great work on this PR. We're making some updates to the course and have decided to remove this Colab. Thanks again.

**Pull request closed without merging**
